[global]
daemonize = no

[www]
listen = 9000
pm.status_path = /fpm-status

pm = dynamic
pm.max_children = 300        ; Max concurrent PHP requests
pm.start_servers = 5         ; workers created at boot
pm.min_spare_servers = 5     ; never fewer than 5 idle
pm.max_spare_servers = 50    ; never fewer than 50 idle
pm.max_requests = 1000       ; Restart worker after N requests to avoid memory leaks