# https://www.digitalocean.com/community/tools/nginx?domains.0.server.domain=sensiolabs.stealth.local&domains.0.server.path=%2Fvar%2Fwww%2Fhtml&domains.0.server.redirectSubdomains=false&domains.0.https.https=false&domains.0.php.phpServer=127.0.0.1%3A9000&global.docker.dockerfile=true&global.app.lang=fr

server {
    listen      80;
    listen      [::]:80;
    server_name ${NGINX_HOST};
    set         $base /var/www/html;
    root        $base/public;

    # security
    # security headers
    add_header X-XSS-Protection        "1; mode=block" always;
    add_header X-Content-Type-Options  "nosniff" always;
    add_header Referrer-Policy         "no-referrer-when-downgrade" always;
    add_header Content-Security-Policy "default-src 'self' data: 'unsafe-inline' script-src 'unsafe-eval' http: https: ws: wss: blob:; frame-ancestors 'self'" always;
    add_header Permissions-Policy      "interest-cohort=()" always;

    # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
    # Must be greater than or equal to the php.ini post_max_size
    client_max_body_size 76m;

    # . files
    location ~ /\.(?!well-known) {
        deny all;
    }

    # logging
    access_log  /var/log/nginx/access.log combined buffer=512k flush=1m;
    error_log   /var/log/nginx/error.log warn;

    # index.php
    index       index.php;

    # index.php fallback
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # additional config
    # favicon.ico
    location = /favicon.ico {
        log_not_found off;
    }

    # robots.txt
    location = /robots.txt {
        log_not_found off;
    }

    # assets, media
    #location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
    #    expires 7d;
    #}

    # svg, fonts
    location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
        add_header Access-Control-Allow-Origin "*";
        expires    7d;
    }

    # gzip
    gzip            on;
    gzip_vary       on;
    gzip_proxied    any;
    gzip_comp_level 6;
    gzip_types      text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

    # Route all /assets/* requests to PHP-FPM
    location /assets/ {
        expires 7d;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # handle .php
    location ~ \.php$ {
        #fastcgi_pass                  unix:/run/php/php8.2-fpm.sock;
        fastcgi_pass                  127.0.0.1:9000;

        
        # 404
        try_files                     $fastcgi_script_name =404;

        # default fastcgi_params
        include                       fastcgi_params;

        # fastcgi settings
        fastcgi_index                 index.php;
        fastcgi_buffers               8 16k;
        fastcgi_buffer_size           32k;

        # fastcgi params
        fastcgi_param DOCUMENT_ROOT   $realpath_root;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location = /metrics {
        fastcgi_pass                  127.0.0.1:9001;
        include                       fastcgi_params;
        fastcgi_param DOCUMENT_ROOT   $realpath_root;
        fastcgi_param SCRIPT_FILENAME $realpath_root/index.php;
        fastcgi_param SCRIPT_NAME     /index.php;
    }

    location ~ ^/fpm-status$ {
        fastcgi_pass                  127.0.0.1:9000;
        include                       fastcgi_params;
        fastcgi_param                 SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

}